### PR TITLE
Add dash license check to CI pipeline

### PR DESCRIPTION
**Pull request by jonahgraham**
Adapted from @ruspl-afed's contribution in
https://github.com/eclipse-cdt/cdt/pull/386

With Orbit being rather large, there are a number of outstanding issues that means this won't successfully complete automatically, so I don't know whether to submit it. I don't know where or how to store the exclusions.

See https://github.com/eclipse/dash-licenses/issues/233 and https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5372#note_1052111 for a couple of examples of where things don't line up.

### CODE REVIEW

**Comment by HannesWell** [comment]
> /request-license-review

Once this is merged, you can use this command to create requests to review the licenses of the unvetted dependencies.
This requires a Eclipse GITLAP API token. I see you have referenced one and assume you already have asked to IP team to include one.
From the initial comment I read that the situation is currently difficult regarding license vetting.

**Comment by jonahgraham** [comment]
The check is now working as expected, the license errors being only:

- [INFO] maven/mavencentral/com.sun.media/jai-codec/1.1.3
- [INFO] maven/mavencentral/javax.media/jai-core/1.1.3

which are indeed errors and waiting on #17 to be fixed to resolve.

**Comment by jonahgraham** [comment]
With the new work being undertaken in https://github.com/eclipse-orbit/orbit-simrel and little to no new commits planned in this repo, investing time in adding license checks here is no longer planned.

**Pull request closed without merging**
